Solved Meta main #524
TuringLang/docs pull request #530
Opened 2024-10-06 11:31 UTC by beingPro007

solved #524 

*Added the meta variables in _quarto.yml*
![Screenshot 2024-10-06 165334](https://github.com/user-attachments/assets/0c193360-0d67-4870-b5cd-63ccc439d653)

and used them here like 
![Screenshot 2024-10-06 165931](https://github.com/user-attachments/assets/ba5eedfb-e782-4392-a3e8-9a5479f90387)

Kindly merge this Pull Request

2024-10-06 11:35 UTC, beingPro007 commented
@yebai Please review this and if correct then merge this to the master branch

2024-10-06 14:44 UTC, beingPro007 commented on _quarto.yml
> -get-started: docs/tutorials/docs-00-getting-started/
1st Change

2024-10-07 11:03 UTC, penelopeysm requested changes
Hi @beingPro007, thanks for working on this 😄 

I have two suggestions for contributing to open source code.

1) Make your commit messages more descriptive. In this case I don't know what 'Meta main 524' is. A better commit message would be `Add Quarto variables`. If you want to make reference to the GitHub issue, you can write a multiline commit message (note that the hashtag, like `#524`, is the usual way of referring to a GitHub issue or pull request):

   ```
   Add Quarto variables
   
   Closes #524
   ```

   In this case, the first line is shown to users and when they look more closely (either via `git log` or via the GitHub web interface) they can see the full message.

   Here's an old, but very good, explanation of what goes into a good commit message: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

2) Use permalinks to refer to code, instead of screenshots. See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet

   Permalinks let you click through to the actual code in the repository, and are also more accessible than screenshots (which can't be read with eg text-to-speech).

2024-10-07 11:20 UTC, beingPro007 commented
@penelopeysm and @yebai I considered this thing as a feedback for this PR and will try to resolve it again and do the following changes as told. Thank you for considering me😁

2024-10-07 14:01 UTC, penelopeysm commented
No problem, feel free to ask if anything is unclear :)

2024-10-07 17:42 UTC, beingPro007 commented on tutorials/04-hidden-markov-model/index.qmd
> +Let's load the libraries we'll need. We also set a random seed (for reproducibility) and the automatic differentiation backend to forward mode (more [here]( {{<meta doc-base-url>}}/{{<meta using-turi
As @yebai said i added {{<meta doc-base-url>}} at the start to avoid ../ or ../../ usage across the tutorials to make the consistency.

2024-10-09 13:43 UTC, penelopeysm approved these changes

2024-10-09 14:13 UTC, beingPro007 commented
@penelopeysm like this way?
![Uploading Screenshot_20241009_194238.jpg…]()

2024-10-09 14:18 UTC, beingPro007 commented
@penelopeysm Like this way? 
![IMG_20241009_194810.jpg](https://github.com/user-attachments/assets/3804814e-15a0-48f9-bde0-d009d7713f79)

2024-10-09 15:09 UTC, penelopeysm commented
Yup!

2024-10-09 15:26 UTC, penelopeysm commented
@yebai I was thinking about maybe introducing a link checker at some point in time to check that the hyperlinks all return 200 :)

2024-10-09 17:16 UTC, penelopeysm commented on _quarto.yml
> +doc-base-url: https://turinglang.org/
I think @yebai is right, turinglang.org itself is fine but if you have `https://turinglang.org/docs/tutorials/01-gaussian-mixture-model/` you can't remove the docs

2024-10-09 20:43 UTC, penelopeysm commented
That's a matter for a separate issue/PR.

2024-10-10 22:55 UTC, merged

2024-10-10 22:57 UTC, penelopeysm commented
(I just did some minor cleanup to get things working nicely.)

Thanks for the contribution, @beingPro007!